### ISSUE TITLE
[Bug] Party view window continuously changing sizes when "Job" stat is selected

### ISSUE THREAD

**Issue by Tischel** [Aireil/FFLogsViewer#30]
https://i.gyazo.com/90f15f6f96bee161eb577ea280c8ef11.gif

**Comment by Aireil** [comment]
Hmmm, I tried reproducing, but even with the update notice I can't. I'm wondering how/why that happens...

**Comment by Tischel** [comment]
Probably depends on the actual data?
Here it is with the update notice dismissed: https://i.gyazo.com/82c0f2e7d4a7bde7b8e1004aafd3d0cd.gif

**Comment by Tischel** [comment]
After 1 player left, it fixed itself.

![image](https://user-images.githubusercontent.com/6404136/222522241-c7483dd6-425c-46df-8d51-75b943b48a64.png)

**Comment by Aireil** [comment]
This is so cursed, I don't even know what could be moving. I'll try reproducing it again later, thanks for the report.

**Comment by Tischel** [comment]
Two new examples:

https://i.gyazo.com/5d06ac36427c66ad7321c833a5fdebe5.gif

https://i.gyazo.com/f3134fc3c530b175fd71da555f9ce861.gif

**Comment by Aireil** [comment]
I'm wondering if that's now fixed in the new version, not sure if you'll play in 6.5, but if you do, please try to check 😄.

Size management is still so bad, I want to rework it one day, SURELY this will happen.

**Comment by Tischel** [comment]
Still happening sadly:

https://i.gyazo.com/010a19a3bc445d2915b0cb402205606b.gif

**Comment by Aireil** [comment]
Big hype, it has been 2 weeks, SURELY this is fixed now!! 😋
